### ISSUE TITLE
deletes it self

### ISSUE THREAD

**Issue by MD211211** [mugman174/togoosestore#2]
ok so i set my settings but every time i close and re open discord it resets

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
> I have not added persistent storage yet, that'll come in the next update.

i hope the next update comes soon, this is really annoying to re-set

**Comment by mugman174** [comment]
> > I have not added persistent storage yet, that'll come in the next update.
> 
> i hope the next update comes soon, this is really annoying to re-set

Sadly I have too much work, so maybe in a month or few I'll be able to do it. Sry :frowning_face:
