### ISSUE TITLE
well same thing, rpc wont enable

### ISSUE THREAD

**Issue by AkaRaxxy** [mugman174/togoosestore#4]
filled every detail carefully and correctly, the enabling slider just goes back to off everytime i click it.

**Comment by DeinMathelehrer** [comment]
+1

**Comment by mugman174** [comment]
yeah I'm working on it now, hopefully next update should fix

sry for late response, been busy

**Comment by LFC6times** [comment]
Has it broken again?

**Comment by LFC6times** [comment]
![image](https://user-images.githubusercontent.com/72238524/167974083-a5cfd931-0367-4ae8-a25a-d0376d04f93a.png)

Checked dev console; this is the error when you attempt to enable it
